server:
  port: 8001

spring:
  mail:
    host: smtp.exmail.qq.com
    port: 465
    protocol: smtp
    username: 58fctmp@58.com
    password: jBREtk9tAwSCDv6j
    test-connection: true
    properties:
      "[mail.smtp.connectiontimeout]": 10000
      "[mail.smtp.timeout]": 10000
      "[mail.smtp.writetimeout]": 10000
      "[mail.smtp.auth]": true
      "[mail.smtp.ssl.enable]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true
  datasource:
    real:
      url: jdbc:mysql://test-fang03.db.58dns.org:53068/db58_house_united?characterEncoding=utf-8&allowMultiQueries=true
      username: houseunited_user
      password: 317a20ae6d56e23f
      driver-class-name: com.mysql.cj.jdbc.Driver
    bug:
      url: jdbc:mysql://test-fang03.db.58dns.org:53068/db58_house_united?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: houseunited_user
      password: 317a20ae6d56e23f
      driver-class-name: com.mysql.cj.jdbc.Driver